version: '3.9'

services:
  mysql:
    image: mysql
    container_name: mysql
    networks:
      - app-network
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=dental_clinic
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
networks:
  app-network:
volumes:
  mysql-data: