definitions:
  domain.Patient:
    properties:
      address:
        type: string
      dni:
        type: string
      id:
        type: integer
      last_name:
        type: string
      name:
        type: string
      registration_date:
        type: string
    required:
    - dni
    - last_name
    - name
    - registration_date
    type: object
  web.ErrorApi:
    properties:
      code:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
externalDocs:
  url: http://localhost:8080/swagger/index.html
host: localhost:8080
info:
  contact:
    email: support@dentalclinic.com
    name: API Support
    url: http://www.dentalclinic.com
  description: This is a API to register a dental shift.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: API Dental Clinic
  version: "1.0"
paths:
  /patients/{id}:
    get:
      description: get patient by ID
      parameters:
      - description: Patient ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Patient'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorApi'
      summary: Show a patient
      tags:
      - patients
swagger: "2.0"
